---
volumes:
  uptimekuma-data:
    driver: local
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    volumes:
      - uptimekuma-data:/app/data
    networks:
      - home-lab
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma-http.rule=Host(`up.jlseholdings.com`)"
      - "traefik.http.routers.uptimekuma-http.entrypoints=web"
      - "traefik.http.routers.uptimekuma-https.rule=Host(`up.jlseholdings.com`)"
      - "traefik.http.routers.uptimekuma-https.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma-https.tls=true"
      - "traefik.http.routers.uptimekuma-https.tls.certresolver=cloudflare"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"

networks:
  home-lab:
    external: true
