---
volumes:
  uptimekuma-data:
    driver: local
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    ports:
      - 3001:3001
    networks:
      br0:
        ipv4_address: 192.168.4.14  # Assign a static IP for AdGuard
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - uptimekuma-data:/app/data
    restart: unless-stopped
    dns:
      - 192.168.4.15
      - 8.8.8.8

networks:
  br0:
    external: true  # Use the already created MacVLAN network

