---
volumes:
  uptimekuma-data:
    driver: local
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    ports:
      - 3001:3001
    network_mode: bridge
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - uptimekuma-data:/app/data
    restart: unless-stopped
    dns:
      - 192.168.4.15
      - 8.8.8.8

