---
volumes:
  uptimekuma-data:
    driver: local
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - uptimekuma-data:/app/data
    restart: unless-stopped


