---
version: '3'

volumes:
  dnsmasq:
    driver: local
  etcd:
    driver: local

networks:
  pihole_macvlan:
    external: true  # Use the already created MacVLAN network

services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:2025.02.4
    networks:
      pihole_macvlan:
        ipv4_address: 192.168.4.15  # Pi-hole's dedicated IP
    environment:
      - TZ=Africa/Johannesburg
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - dnsmasq:/etc/dnsmasq.d
      - etcd:/etc/pihole
      - /mnt/user/Docker/Home-Lab-Docker-Compose/pihole/dnsmasqd/02-wildcard.conf:/etc/dnsmasq.d/02-wildcard.conf:ro
    restart: unless-stopped
