---
version: '3.8'

services:
  traefik:
    image: docker.io/library/traefik:v3.3.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8082:8082  # Expose only Prometheus metrics
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - /mnt/user/Docker/Home-Lab-Docker-Compose/traefik/config/:/etc/traefik/:ro
      - /mnt/user/Docker/Home-Lab-Docker-Compose/traefik/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}  # Cloudflare API Token for certs
    networks:
      - home-lab
    restart: unless-stopped
    command:
      - "--api.dashboard=false"  # Disable Traefik dashboard
      - "--api.insecure=false"   # Block insecure API exposure
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8082"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metrics.rule=Host(`traefik.metrics.jlseholdings.com`)"
      - "traefik.http.routers.metrics.entrypoints=websecure"
      - "traefik.http.routers.metrics.tls=true"
      - "traefik.http.services.metrics.loadbalancer.server.port=8082"

networks:
  home-lab:
    external: true  # Keep using the existing network
