---
services:
  traefik:
    image: docker.io/library/traefik:v3.3.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8085:8080  # Secure Dashboard access
      - 8082:8082  # Expose Prometheus metrics for monitoring
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - /mnt/user/Docker/Home-Lab-Docker-Compose/traefik/config/:/etc/traefik/:ro
      - /mnt/user/Docker/Home-Lab-Docker-Compose/traefik/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}  # Cloudflare API Token for certs
    networks:
      - home-lab
    restart: unless-stopped

networks:
  home-lab:
    external: true  # Keep using the existing network
