version: '3.8'

services:
  traefik:
    image: docker.io/library/traefik:v3.3.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8085:8080
      - 8899:8899  # Exposing the Prometheus metrics port

    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - /mnt/user/Docker/Home-Lab-Docker-Compose/traefik/config/:/etc/traefik/:ro
      - /mnt/user/Docker/Home-Lab-Docker-Compose/traefik/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - home-lab
    restart: unless-stopped
    command:
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8899"  # Dedicated metrics entrypoint
      - "--providers.docker=true"
      - "--providers.docker.watch"
    labels:
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.jlseholdings.com`)"
      - "traefik.http.routers.traefik-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-https.service=api@internal"

networks:
  home-lab:
    external: true
