---
volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana runs internally on port 3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - home-lab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-http.rule=Host(`grafana.jlseholdings.com`)"
      - "traefik.http.routers.grafana-http.entrypoints=web"
      - "traefik.http.routers.grafana-https.rule=Host(`grafana.jlseholdings.com`)"
      - "traefik.http.routers.grafana-https.entrypoints=websecure"
      - "traefik.http.routers.grafana-https.tls=true"
      - "traefik.http.routers.grafana-https.tls.certresolver=godaddy"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  home-lab:
    external: true
