---
volumes:
  grafana-data:
    driver: local
services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - home-lab
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-http. rule=Host(grafana.jlseholdings.com' )
      - traefik.http.routers.nginx-http.entrypoints=web
      - traefik.http.routers.nginx-https.tls=true
      - traefik.http.routers.nginx-https.certresolver=cloudflare
      - traefik.http.routers.nginx-https.entrypoints=websecure
      - traefik.http.routers.nginx-https.rule=Host(grafana.jlseholdings.com')
      # - "traefik.http.routers.homarr.tls.certresolver=le"
