---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    environment:
      - LOG_LEVEL=info
    # (Optional) Run as a specific user
    #   - PUID=your-user-id
    #   - PGID=your-group-id
    # (Optional) For secret variables
    #   - HOMEPAGE_VAR_YOURSECRET=your-secret-key
    volumes:
      - /mnt/user/Docker/Home-Lab-Docker-Compose/homepage/config:/app/config
      - /mnt/user/Docker/Home-Lab-Docker-Compose/homepage/images:/app/images  # for custom background images
      - /mnt/user/Docker/Home-Lab-Docker-Compose/homepage/icons:/app/icons  # for custom icons
#   (Optional) For secure docker socket integration
#   dockerproxy:
#     image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
#     container_name: homepage-demo-1-dockerproxy
#     environment:
#       - CONTAINERS=1 # Allow access to viewing containers
#       - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
#       - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
#       - POST=0 # Disallow any POST operations (effectively read-only)
#     ports:
#       - 127.0.0.1:2375:2375
#     volumes:
#       - /run/docker.sock:/run/docker.sock:ro # Mounted as read-only
#     restart: unless-stopped
    networks:
      - home-lab
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-http.rule=Host(`prometheus.jlseholdings.com`)"
      - "traefik.http.routers.homepage-http.entrypoints=web"
      - "traefik.http.routers.homepage-https.rule=Host(`prometheus.jlseholdings.com`)"
      - "traefik.http.routers.homepage-https.entrypoints=websecure"
      - "traefik.http.routers.homepage-https.tls=true"
      - "traefik.http.routers.homepage-https.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  home-lab:
    external: true
