---
version: '3'
networks:
  br0:
    external: true  # Use the already created MacVLAN network

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    networks:
      br0:
        ipv4_address: 192.168.4.16  # Assign a static IP for AdGuard
    environment:
      - TZ=Africa/Johannesburg
    restart: unless-stopped
    cap_add:
      - NET_ADMIN  # Required for DNS and DHCP handling
    ports:
      - "53:53/tcp"     # DNS over TCP
      - "53:53/udp"     # DNS over UDP
      - "67:67/udp"     # DHCP (if you use it)
      - "80:80/tcp"     # Web UI (HTTP)
      - "443:443/tcp"   # DNS over HTTPS
      - "853:853/tcp"   # DNS over TLS
      - "3000:3000/tcp" # Initial setup page
